---
- name: "Install the httpd package and start service"
  hosts: all
  gather_facts: False
  tasks:
  - name:  Install httpd
    yum:
      name: httpd
      state: present

  - name: start httpd service
    service: 
      name: httpd
      state: started

